[project]
name = "nomad-train"
version = "0.1.0"
requires-python = "==3.8.20"

dependencies = [
    "numpy",
    "matplotlib",
    "ipykernel",
    "tqdm==4.64.0",
    "opencv-python==4.6.0.66",
    "h5py==3.6.0",
    "wandb==0.12.18",
    "prettytable",
    "efficientnet-pytorch",
    "diffusers==0.11.1",
    "lmdb",
    "vit-pytorch",
    "positional-encodings",
    # Git dependency
    "warmup-scheduler @ git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git",
    # ROS pip源的包
    "rosbag",
    "roslz4",
    "torch>=2.4.1",
    "huggingface-hub==0.25.2",
    "sensor-msgs>=1.13.0.post3",
    "geometry-msgs>=1.13.0.post2",
    "pandas>=2.0.3",
]

[tool.uv]
# 额外 index（替代 --extra-index-url）
extra-index-url = ["https://rospypi.github.io/simple/"]
